package com.it.zqm.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TNsTypeInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public TNsTypeInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSliceTypeIdIsNull() {
            addCriterion("slice_type_id is null");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdIsNotNull() {
            addCriterion("slice_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdEqualTo(String value) {
            addCriterion("slice_type_id =", value, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdNotEqualTo(String value) {
            addCriterion("slice_type_id <>", value, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdGreaterThan(String value) {
            addCriterion("slice_type_id >", value, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("slice_type_id >=", value, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdLessThan(String value) {
            addCriterion("slice_type_id <", value, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdLessThanOrEqualTo(String value) {
            addCriterion("slice_type_id <=", value, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdLike(String value) {
            addCriterion("slice_type_id like", value, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdNotLike(String value) {
            addCriterion("slice_type_id not like", value, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdIn(List<String> values) {
            addCriterion("slice_type_id in", values, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdNotIn(List<String> values) {
            addCriterion("slice_type_id not in", values, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdBetween(String value1, String value2) {
            addCriterion("slice_type_id between", value1, value2, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeIdNotBetween(String value1, String value2) {
            addCriterion("slice_type_id not between", value1, value2, "sliceTypeId");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameIsNull() {
            addCriterion("slice_type_name is null");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameIsNotNull() {
            addCriterion("slice_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameEqualTo(String value) {
            addCriterion("slice_type_name =", value, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameNotEqualTo(String value) {
            addCriterion("slice_type_name <>", value, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameGreaterThan(String value) {
            addCriterion("slice_type_name >", value, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("slice_type_name >=", value, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameLessThan(String value) {
            addCriterion("slice_type_name <", value, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameLessThanOrEqualTo(String value) {
            addCriterion("slice_type_name <=", value, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameLike(String value) {
            addCriterion("slice_type_name like", value, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameNotLike(String value) {
            addCriterion("slice_type_name not like", value, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameIn(List<String> values) {
            addCriterion("slice_type_name in", values, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameNotIn(List<String> values) {
            addCriterion("slice_type_name not in", values, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameBetween(String value1, String value2) {
            addCriterion("slice_type_name between", value1, value2, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andSliceTypeNameNotBetween(String value1, String value2) {
            addCriterion("slice_type_name not between", value1, value2, "sliceTypeName");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdIsNull() {
            addCriterion("end_to_end_mapping_id is null");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdIsNotNull() {
            addCriterion("end_to_end_mapping_id is not null");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdEqualTo(String value) {
            addCriterion("end_to_end_mapping_id =", value, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdNotEqualTo(String value) {
            addCriterion("end_to_end_mapping_id <>", value, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdGreaterThan(String value) {
            addCriterion("end_to_end_mapping_id >", value, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdGreaterThanOrEqualTo(String value) {
            addCriterion("end_to_end_mapping_id >=", value, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdLessThan(String value) {
            addCriterion("end_to_end_mapping_id <", value, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdLessThanOrEqualTo(String value) {
            addCriterion("end_to_end_mapping_id <=", value, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdLike(String value) {
            addCriterion("end_to_end_mapping_id like", value, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdNotLike(String value) {
            addCriterion("end_to_end_mapping_id not like", value, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdIn(List<String> values) {
            addCriterion("end_to_end_mapping_id in", values, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdNotIn(List<String> values) {
            addCriterion("end_to_end_mapping_id not in", values, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdBetween(String value1, String value2) {
            addCriterion("end_to_end_mapping_id between", value1, value2, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andEndToEndMappingIdNotBetween(String value1, String value2) {
            addCriterion("end_to_end_mapping_id not between", value1, value2, "endToEndMappingId");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeIsNull() {
            addCriterion("ul_thpt_per_ue is null");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeIsNotNull() {
            addCriterion("ul_thpt_per_ue is not null");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeEqualTo(String value) {
            addCriterion("ul_thpt_per_ue =", value, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeNotEqualTo(String value) {
            addCriterion("ul_thpt_per_ue <>", value, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeGreaterThan(String value) {
            addCriterion("ul_thpt_per_ue >", value, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeGreaterThanOrEqualTo(String value) {
            addCriterion("ul_thpt_per_ue >=", value, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeLessThan(String value) {
            addCriterion("ul_thpt_per_ue <", value, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeLessThanOrEqualTo(String value) {
            addCriterion("ul_thpt_per_ue <=", value, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeLike(String value) {
            addCriterion("ul_thpt_per_ue like", value, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeNotLike(String value) {
            addCriterion("ul_thpt_per_ue not like", value, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeIn(List<String> values) {
            addCriterion("ul_thpt_per_ue in", values, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeNotIn(List<String> values) {
            addCriterion("ul_thpt_per_ue not in", values, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeBetween(String value1, String value2) {
            addCriterion("ul_thpt_per_ue between", value1, value2, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeNotBetween(String value1, String value2) {
            addCriterion("ul_thpt_per_ue not between", value1, value2, "ulThptPerUe");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeIsNull() {
            addCriterion("ul_thpt_per_ue_scope is null");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeIsNotNull() {
            addCriterion("ul_thpt_per_ue_scope is not null");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeEqualTo(String value) {
            addCriterion("ul_thpt_per_ue_scope =", value, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeNotEqualTo(String value) {
            addCriterion("ul_thpt_per_ue_scope <>", value, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeGreaterThan(String value) {
            addCriterion("ul_thpt_per_ue_scope >", value, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeGreaterThanOrEqualTo(String value) {
            addCriterion("ul_thpt_per_ue_scope >=", value, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeLessThan(String value) {
            addCriterion("ul_thpt_per_ue_scope <", value, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeLessThanOrEqualTo(String value) {
            addCriterion("ul_thpt_per_ue_scope <=", value, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeLike(String value) {
            addCriterion("ul_thpt_per_ue_scope like", value, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeNotLike(String value) {
            addCriterion("ul_thpt_per_ue_scope not like", value, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeIn(List<String> values) {
            addCriterion("ul_thpt_per_ue_scope in", values, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeNotIn(List<String> values) {
            addCriterion("ul_thpt_per_ue_scope not in", values, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeBetween(String value1, String value2) {
            addCriterion("ul_thpt_per_ue_scope between", value1, value2, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerUeScopeNotBetween(String value1, String value2) {
            addCriterion("ul_thpt_per_ue_scope not between", value1, value2, "ulThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeIsNull() {
            addCriterion("dl_thpt_per_ue is null");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeIsNotNull() {
            addCriterion("dl_thpt_per_ue is not null");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeEqualTo(String value) {
            addCriterion("dl_thpt_per_ue =", value, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeNotEqualTo(String value) {
            addCriterion("dl_thpt_per_ue <>", value, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeGreaterThan(String value) {
            addCriterion("dl_thpt_per_ue >", value, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeGreaterThanOrEqualTo(String value) {
            addCriterion("dl_thpt_per_ue >=", value, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeLessThan(String value) {
            addCriterion("dl_thpt_per_ue <", value, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeLessThanOrEqualTo(String value) {
            addCriterion("dl_thpt_per_ue <=", value, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeLike(String value) {
            addCriterion("dl_thpt_per_ue like", value, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeNotLike(String value) {
            addCriterion("dl_thpt_per_ue not like", value, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeIn(List<String> values) {
            addCriterion("dl_thpt_per_ue in", values, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeNotIn(List<String> values) {
            addCriterion("dl_thpt_per_ue not in", values, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeBetween(String value1, String value2) {
            addCriterion("dl_thpt_per_ue between", value1, value2, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeNotBetween(String value1, String value2) {
            addCriterion("dl_thpt_per_ue not between", value1, value2, "dlThptPerUe");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeIsNull() {
            addCriterion("dl_thpt_per_ue_scope is null");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeIsNotNull() {
            addCriterion("dl_thpt_per_ue_scope is not null");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeEqualTo(String value) {
            addCriterion("dl_thpt_per_ue_scope =", value, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeNotEqualTo(String value) {
            addCriterion("dl_thpt_per_ue_scope <>", value, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeGreaterThan(String value) {
            addCriterion("dl_thpt_per_ue_scope >", value, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeGreaterThanOrEqualTo(String value) {
            addCriterion("dl_thpt_per_ue_scope >=", value, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeLessThan(String value) {
            addCriterion("dl_thpt_per_ue_scope <", value, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeLessThanOrEqualTo(String value) {
            addCriterion("dl_thpt_per_ue_scope <=", value, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeLike(String value) {
            addCriterion("dl_thpt_per_ue_scope like", value, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeNotLike(String value) {
            addCriterion("dl_thpt_per_ue_scope not like", value, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeIn(List<String> values) {
            addCriterion("dl_thpt_per_ue_scope in", values, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeNotIn(List<String> values) {
            addCriterion("dl_thpt_per_ue_scope not in", values, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeBetween(String value1, String value2) {
            addCriterion("dl_thpt_per_ue_scope between", value1, value2, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerUeScopeNotBetween(String value1, String value2) {
            addCriterion("dl_thpt_per_ue_scope not between", value1, value2, "dlThptPerUeScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceIsNull() {
            addCriterion("ul_thpt_per_slice is null");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceIsNotNull() {
            addCriterion("ul_thpt_per_slice is not null");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceEqualTo(String value) {
            addCriterion("ul_thpt_per_slice =", value, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceNotEqualTo(String value) {
            addCriterion("ul_thpt_per_slice <>", value, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceGreaterThan(String value) {
            addCriterion("ul_thpt_per_slice >", value, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceGreaterThanOrEqualTo(String value) {
            addCriterion("ul_thpt_per_slice >=", value, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceLessThan(String value) {
            addCriterion("ul_thpt_per_slice <", value, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceLessThanOrEqualTo(String value) {
            addCriterion("ul_thpt_per_slice <=", value, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceLike(String value) {
            addCriterion("ul_thpt_per_slice like", value, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceNotLike(String value) {
            addCriterion("ul_thpt_per_slice not like", value, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceIn(List<String> values) {
            addCriterion("ul_thpt_per_slice in", values, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceNotIn(List<String> values) {
            addCriterion("ul_thpt_per_slice not in", values, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceBetween(String value1, String value2) {
            addCriterion("ul_thpt_per_slice between", value1, value2, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceNotBetween(String value1, String value2) {
            addCriterion("ul_thpt_per_slice not between", value1, value2, "ulThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeIsNull() {
            addCriterion("ul_thpt_per_slice_scope is null");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeIsNotNull() {
            addCriterion("ul_thpt_per_slice_scope is not null");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeEqualTo(String value) {
            addCriterion("ul_thpt_per_slice_scope =", value, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeNotEqualTo(String value) {
            addCriterion("ul_thpt_per_slice_scope <>", value, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeGreaterThan(String value) {
            addCriterion("ul_thpt_per_slice_scope >", value, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeGreaterThanOrEqualTo(String value) {
            addCriterion("ul_thpt_per_slice_scope >=", value, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeLessThan(String value) {
            addCriterion("ul_thpt_per_slice_scope <", value, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeLessThanOrEqualTo(String value) {
            addCriterion("ul_thpt_per_slice_scope <=", value, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeLike(String value) {
            addCriterion("ul_thpt_per_slice_scope like", value, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeNotLike(String value) {
            addCriterion("ul_thpt_per_slice_scope not like", value, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeIn(List<String> values) {
            addCriterion("ul_thpt_per_slice_scope in", values, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeNotIn(List<String> values) {
            addCriterion("ul_thpt_per_slice_scope not in", values, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeBetween(String value1, String value2) {
            addCriterion("ul_thpt_per_slice_scope between", value1, value2, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andUlThptPerSliceScopeNotBetween(String value1, String value2) {
            addCriterion("ul_thpt_per_slice_scope not between", value1, value2, "ulThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceIsNull() {
            addCriterion("dl_thpt_per_slice is null");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceIsNotNull() {
            addCriterion("dl_thpt_per_slice is not null");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceEqualTo(String value) {
            addCriterion("dl_thpt_per_slice =", value, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceNotEqualTo(String value) {
            addCriterion("dl_thpt_per_slice <>", value, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceGreaterThan(String value) {
            addCriterion("dl_thpt_per_slice >", value, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceGreaterThanOrEqualTo(String value) {
            addCriterion("dl_thpt_per_slice >=", value, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceLessThan(String value) {
            addCriterion("dl_thpt_per_slice <", value, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceLessThanOrEqualTo(String value) {
            addCriterion("dl_thpt_per_slice <=", value, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceLike(String value) {
            addCriterion("dl_thpt_per_slice like", value, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceNotLike(String value) {
            addCriterion("dl_thpt_per_slice not like", value, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceIn(List<String> values) {
            addCriterion("dl_thpt_per_slice in", values, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceNotIn(List<String> values) {
            addCriterion("dl_thpt_per_slice not in", values, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceBetween(String value1, String value2) {
            addCriterion("dl_thpt_per_slice between", value1, value2, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceNotBetween(String value1, String value2) {
            addCriterion("dl_thpt_per_slice not between", value1, value2, "dlThptPerSlice");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeIsNull() {
            addCriterion("dl_thpt_per_slice_scope is null");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeIsNotNull() {
            addCriterion("dl_thpt_per_slice_scope is not null");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeEqualTo(String value) {
            addCriterion("dl_thpt_per_slice_scope =", value, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeNotEqualTo(String value) {
            addCriterion("dl_thpt_per_slice_scope <>", value, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeGreaterThan(String value) {
            addCriterion("dl_thpt_per_slice_scope >", value, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeGreaterThanOrEqualTo(String value) {
            addCriterion("dl_thpt_per_slice_scope >=", value, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeLessThan(String value) {
            addCriterion("dl_thpt_per_slice_scope <", value, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeLessThanOrEqualTo(String value) {
            addCriterion("dl_thpt_per_slice_scope <=", value, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeLike(String value) {
            addCriterion("dl_thpt_per_slice_scope like", value, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeNotLike(String value) {
            addCriterion("dl_thpt_per_slice_scope not like", value, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeIn(List<String> values) {
            addCriterion("dl_thpt_per_slice_scope in", values, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeNotIn(List<String> values) {
            addCriterion("dl_thpt_per_slice_scope not in", values, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeBetween(String value1, String value2) {
            addCriterion("dl_thpt_per_slice_scope between", value1, value2, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andDlThptPerSliceScopeNotBetween(String value1, String value2) {
            addCriterion("dl_thpt_per_slice_scope not between", value1, value2, "dlThptPerSliceScope");
            return (Criteria) this;
        }

        public Criteria andLatencyIsNull() {
            addCriterion("latency is null");
            return (Criteria) this;
        }

        public Criteria andLatencyIsNotNull() {
            addCriterion("latency is not null");
            return (Criteria) this;
        }

        public Criteria andLatencyEqualTo(String value) {
            addCriterion("latency =", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyNotEqualTo(String value) {
            addCriterion("latency <>", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyGreaterThan(String value) {
            addCriterion("latency >", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyGreaterThanOrEqualTo(String value) {
            addCriterion("latency >=", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyLessThan(String value) {
            addCriterion("latency <", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyLessThanOrEqualTo(String value) {
            addCriterion("latency <=", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyLike(String value) {
            addCriterion("latency like", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyNotLike(String value) {
            addCriterion("latency not like", value, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyIn(List<String> values) {
            addCriterion("latency in", values, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyNotIn(List<String> values) {
            addCriterion("latency not in", values, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyBetween(String value1, String value2) {
            addCriterion("latency between", value1, value2, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyNotBetween(String value1, String value2) {
            addCriterion("latency not between", value1, value2, "latency");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeIsNull() {
            addCriterion("latency_scope is null");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeIsNotNull() {
            addCriterion("latency_scope is not null");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeEqualTo(String value) {
            addCriterion("latency_scope =", value, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeNotEqualTo(String value) {
            addCriterion("latency_scope <>", value, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeGreaterThan(String value) {
            addCriterion("latency_scope >", value, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeGreaterThanOrEqualTo(String value) {
            addCriterion("latency_scope >=", value, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeLessThan(String value) {
            addCriterion("latency_scope <", value, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeLessThanOrEqualTo(String value) {
            addCriterion("latency_scope <=", value, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeLike(String value) {
            addCriterion("latency_scope like", value, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeNotLike(String value) {
            addCriterion("latency_scope not like", value, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeIn(List<String> values) {
            addCriterion("latency_scope in", values, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeNotIn(List<String> values) {
            addCriterion("latency_scope not in", values, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeBetween(String value1, String value2) {
            addCriterion("latency_scope between", value1, value2, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andLatencyScopeNotBetween(String value1, String value2) {
            addCriterion("latency_scope not between", value1, value2, "latencyScope");
            return (Criteria) this;
        }

        public Criteria andMobilityIsNull() {
            addCriterion("mobility is null");
            return (Criteria) this;
        }

        public Criteria andMobilityIsNotNull() {
            addCriterion("mobility is not null");
            return (Criteria) this;
        }

        public Criteria andMobilityEqualTo(String value) {
            addCriterion("mobility =", value, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityNotEqualTo(String value) {
            addCriterion("mobility <>", value, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityGreaterThan(String value) {
            addCriterion("mobility >", value, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityGreaterThanOrEqualTo(String value) {
            addCriterion("mobility >=", value, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityLessThan(String value) {
            addCriterion("mobility <", value, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityLessThanOrEqualTo(String value) {
            addCriterion("mobility <=", value, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityLike(String value) {
            addCriterion("mobility like", value, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityNotLike(String value) {
            addCriterion("mobility not like", value, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityIn(List<String> values) {
            addCriterion("mobility in", values, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityNotIn(List<String> values) {
            addCriterion("mobility not in", values, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityBetween(String value1, String value2) {
            addCriterion("mobility between", value1, value2, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityNotBetween(String value1, String value2) {
            addCriterion("mobility not between", value1, value2, "mobility");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeIsNull() {
            addCriterion("mobility_scope is null");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeIsNotNull() {
            addCriterion("mobility_scope is not null");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeEqualTo(String value) {
            addCriterion("mobility_scope =", value, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeNotEqualTo(String value) {
            addCriterion("mobility_scope <>", value, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeGreaterThan(String value) {
            addCriterion("mobility_scope >", value, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeGreaterThanOrEqualTo(String value) {
            addCriterion("mobility_scope >=", value, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeLessThan(String value) {
            addCriterion("mobility_scope <", value, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeLessThanOrEqualTo(String value) {
            addCriterion("mobility_scope <=", value, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeLike(String value) {
            addCriterion("mobility_scope like", value, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeNotLike(String value) {
            addCriterion("mobility_scope not like", value, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeIn(List<String> values) {
            addCriterion("mobility_scope in", values, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeNotIn(List<String> values) {
            addCriterion("mobility_scope not in", values, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeBetween(String value1, String value2) {
            addCriterion("mobility_scope between", value1, value2, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andMobilityScopeNotBetween(String value1, String value2) {
            addCriterion("mobility_scope not between", value1, value2, "mobilityScope");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIsNull() {
            addCriterion("delete_status is null");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIsNotNull() {
            addCriterion("delete_status is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusEqualTo(Integer value) {
            addCriterion("delete_status =", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotEqualTo(Integer value) {
            addCriterion("delete_status <>", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusGreaterThan(Integer value) {
            addCriterion("delete_status >", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("delete_status >=", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusLessThan(Integer value) {
            addCriterion("delete_status <", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusLessThanOrEqualTo(Integer value) {
            addCriterion("delete_status <=", value, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusIn(List<Integer> values) {
            addCriterion("delete_status in", values, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotIn(List<Integer> values) {
            addCriterion("delete_status not in", values, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusBetween(Integer value1, Integer value2) {
            addCriterion("delete_status between", value1, value2, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andDeleteStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("delete_status not between", value1, value2, "deleteStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ns_type_info
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 18 11:31:13 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}