package com.it.zqm.dao.entity;

import java.util.Date;

public class TNsTypeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.slice_type_id
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String sliceTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.slice_type_name
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String sliceTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.end_to_end_mapping_id
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String endToEndMappingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.ul_thpt_per_ue
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String ulThptPerUe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.ul_thpt_per_ue_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String ulThptPerUeScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.dl_thpt_per_ue
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String dlThptPerUe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.dl_thpt_per_ue_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String dlThptPerUeScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.ul_thpt_per_slice
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String ulThptPerSlice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.ul_thpt_per_slice_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String ulThptPerSliceScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.dl_thpt_per_slice
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String dlThptPerSlice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.dl_thpt_per_slice_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String dlThptPerSliceScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.latency
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String latency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.latency_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String latencyScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.mobility
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String mobility;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.mobility_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private String mobilityScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.status
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.delete_status
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private Integer deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.update_time
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ns_type_info.create_time
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.slice_type_id
     *
     * @return the value of t_ns_type_info.slice_type_id
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getSliceTypeId() {
        return sliceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.slice_type_id
     *
     * @param sliceTypeId the value for t_ns_type_info.slice_type_id
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setSliceTypeId(String sliceTypeId) {
        this.sliceTypeId = sliceTypeId == null ? null : sliceTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.slice_type_name
     *
     * @return the value of t_ns_type_info.slice_type_name
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getSliceTypeName() {
        return sliceTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.slice_type_name
     *
     * @param sliceTypeName the value for t_ns_type_info.slice_type_name
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setSliceTypeName(String sliceTypeName) {
        this.sliceTypeName = sliceTypeName == null ? null : sliceTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.end_to_end_mapping_id
     *
     * @return the value of t_ns_type_info.end_to_end_mapping_id
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getEndToEndMappingId() {
        return endToEndMappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.end_to_end_mapping_id
     *
     * @param endToEndMappingId the value for t_ns_type_info.end_to_end_mapping_id
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setEndToEndMappingId(String endToEndMappingId) {
        this.endToEndMappingId = endToEndMappingId == null ? null : endToEndMappingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.ul_thpt_per_ue
     *
     * @return the value of t_ns_type_info.ul_thpt_per_ue
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getUlThptPerUe() {
        return ulThptPerUe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.ul_thpt_per_ue
     *
     * @param ulThptPerUe the value for t_ns_type_info.ul_thpt_per_ue
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setUlThptPerUe(String ulThptPerUe) {
        this.ulThptPerUe = ulThptPerUe == null ? null : ulThptPerUe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.ul_thpt_per_ue_scope
     *
     * @return the value of t_ns_type_info.ul_thpt_per_ue_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getUlThptPerUeScope() {
        return ulThptPerUeScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.ul_thpt_per_ue_scope
     *
     * @param ulThptPerUeScope the value for t_ns_type_info.ul_thpt_per_ue_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setUlThptPerUeScope(String ulThptPerUeScope) {
        this.ulThptPerUeScope = ulThptPerUeScope == null ? null : ulThptPerUeScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.dl_thpt_per_ue
     *
     * @return the value of t_ns_type_info.dl_thpt_per_ue
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getDlThptPerUe() {
        return dlThptPerUe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.dl_thpt_per_ue
     *
     * @param dlThptPerUe the value for t_ns_type_info.dl_thpt_per_ue
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setDlThptPerUe(String dlThptPerUe) {
        this.dlThptPerUe = dlThptPerUe == null ? null : dlThptPerUe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.dl_thpt_per_ue_scope
     *
     * @return the value of t_ns_type_info.dl_thpt_per_ue_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getDlThptPerUeScope() {
        return dlThptPerUeScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.dl_thpt_per_ue_scope
     *
     * @param dlThptPerUeScope the value for t_ns_type_info.dl_thpt_per_ue_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setDlThptPerUeScope(String dlThptPerUeScope) {
        this.dlThptPerUeScope = dlThptPerUeScope == null ? null : dlThptPerUeScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.ul_thpt_per_slice
     *
     * @return the value of t_ns_type_info.ul_thpt_per_slice
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getUlThptPerSlice() {
        return ulThptPerSlice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.ul_thpt_per_slice
     *
     * @param ulThptPerSlice the value for t_ns_type_info.ul_thpt_per_slice
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setUlThptPerSlice(String ulThptPerSlice) {
        this.ulThptPerSlice = ulThptPerSlice == null ? null : ulThptPerSlice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.ul_thpt_per_slice_scope
     *
     * @return the value of t_ns_type_info.ul_thpt_per_slice_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getUlThptPerSliceScope() {
        return ulThptPerSliceScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.ul_thpt_per_slice_scope
     *
     * @param ulThptPerSliceScope the value for t_ns_type_info.ul_thpt_per_slice_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setUlThptPerSliceScope(String ulThptPerSliceScope) {
        this.ulThptPerSliceScope = ulThptPerSliceScope == null ? null : ulThptPerSliceScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.dl_thpt_per_slice
     *
     * @return the value of t_ns_type_info.dl_thpt_per_slice
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getDlThptPerSlice() {
        return dlThptPerSlice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.dl_thpt_per_slice
     *
     * @param dlThptPerSlice the value for t_ns_type_info.dl_thpt_per_slice
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setDlThptPerSlice(String dlThptPerSlice) {
        this.dlThptPerSlice = dlThptPerSlice == null ? null : dlThptPerSlice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.dl_thpt_per_slice_scope
     *
     * @return the value of t_ns_type_info.dl_thpt_per_slice_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getDlThptPerSliceScope() {
        return dlThptPerSliceScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.dl_thpt_per_slice_scope
     *
     * @param dlThptPerSliceScope the value for t_ns_type_info.dl_thpt_per_slice_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setDlThptPerSliceScope(String dlThptPerSliceScope) {
        this.dlThptPerSliceScope = dlThptPerSliceScope == null ? null : dlThptPerSliceScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.latency
     *
     * @return the value of t_ns_type_info.latency
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getLatency() {
        return latency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.latency
     *
     * @param latency the value for t_ns_type_info.latency
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setLatency(String latency) {
        this.latency = latency == null ? null : latency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.latency_scope
     *
     * @return the value of t_ns_type_info.latency_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getLatencyScope() {
        return latencyScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.latency_scope
     *
     * @param latencyScope the value for t_ns_type_info.latency_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setLatencyScope(String latencyScope) {
        this.latencyScope = latencyScope == null ? null : latencyScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.mobility
     *
     * @return the value of t_ns_type_info.mobility
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getMobility() {
        return mobility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.mobility
     *
     * @param mobility the value for t_ns_type_info.mobility
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setMobility(String mobility) {
        this.mobility = mobility == null ? null : mobility.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.mobility_scope
     *
     * @return the value of t_ns_type_info.mobility_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public String getMobilityScope() {
        return mobilityScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.mobility_scope
     *
     * @param mobilityScope the value for t_ns_type_info.mobility_scope
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setMobilityScope(String mobilityScope) {
        this.mobilityScope = mobilityScope == null ? null : mobilityScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.status
     *
     * @return the value of t_ns_type_info.status
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.status
     *
     * @param status the value for t_ns_type_info.status
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.delete_status
     *
     * @return the value of t_ns_type_info.delete_status
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.delete_status
     *
     * @param deleteStatus the value for t_ns_type_info.delete_status
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.update_time
     *
     * @return the value of t_ns_type_info.update_time
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.update_time
     *
     * @param updateTime the value for t_ns_type_info.update_time
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ns_type_info.create_time
     *
     * @return the value of t_ns_type_info.create_time
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ns_type_info.create_time
     *
     * @param createTime the value for t_ns_type_info.create_time
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}