
# 指定运行环境
spring:
  profiles:
    active: test
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zqm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=FALSE&serverTimezone=GMT%2B8
      username: root
      password: Sylincom123#@!

  # 配置应用名称
  application:
    name: zeus
  output:
    ansi:
      enabled: ALWAYS
server:
  # 服务端口
  port: 8081
  servlet:
    # 项目contextPath
    context-path: /zeus
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ict.ac
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  #configLocation: classpath:mapper/mybatis-config.xml
  #控制台打mybatits的sql
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
# 数据源配置

logging:
  # 配置日志文件路径
  config: classpath:logback-spring.xml
  # 配置是否需要记录操作日志
  record:
    operate-log: true

debug: true

test:
  read:
    message:

executorPool:
  executorMaxPoolSize: 64
  executorCoreSize: 32
  keepAliveSeconds: 60
  queueCapacity: 10

package:
  version: v1.0
  branch: test1