package com.it.zqm.dao.mapper;

import com.it.zqm.dao.entity.TNsTypeInfo;
import com.it.zqm.dao.entity.TNsTypeInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TNsTypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    long countByExample(TNsTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    int deleteByExample(TNsTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    int insert(TNsTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    int insertSelective(TNsTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    List<TNsTypeInfo> selectByExampleWithRowbounds(TNsTypeInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    List<TNsTypeInfo> selectByExample(TNsTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") TNsTypeInfo record, @Param("example") TNsTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ns_type_info
     *
     * @mbg.generated Sat Sep 18 11:31:13 CST 2021
     */
    int updateByExample(@Param("record") TNsTypeInfo record, @Param("example") TNsTypeInfoExample example);
}